# =========================
# Network & Volumes
# =========================
networks:
  pipeline-net:
    driver: bridge

volumes:
  postgres-db-volume:
  postgres-app-volume:
  redis-data:
  kafka-data:
  redis-cache-data:

# =========================
# Airflow Common
# =========================
x-airflow-common: &airflow-common
  build: ./docker/airflow
  env_file:
    - .env
  networks:
    - pipeline-net
  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW__CELERY__BROKER_URL}
    AIRFLOW__CELERY__RESULT_BACKEND: ${AIRFLOW__CELERY__RESULT_BACKEND}
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
    AIRFLOW__CORE__DAGS_FOLDER: /opt/project/src/dags
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
    PYTHONPATH: /opt/project/src/lib

  volumes:
    - ./src:/opt/project/src
    - ./src/plugins:/opt/airflow/plugins
    - ./src/logs:/opt/airflow/logs

  user: "${AIRFLOW_UID:-50000}:0"

  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
    kafka:
      condition: service_healthy

# =========================
# Services
# =========================
services:

  # ---------- Postgres ----------
  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - pipeline-net
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # ---------- Redis ----------
  redis:
    image: redis:7.2-bookworm
    container_name: redis
    networks:
      - pipeline-net
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


  # ---------- Kafka ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    networks:
      - pipeline-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    networks:
      - pipeline-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 72
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  # ---------- Spark Master ----------
  spark-master:
    build:
      context: ./docker/spark  
      dockerfile: Dockerfile
    container_name: spark-master
    env_file:
    - .env
    networks:
      - pipeline-net
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master 
    ports:
      - "7078:7077"
      - "8081:8080"
    environment:
      PYTHONPATH: /opt/project/src
      SPARK_SUBMIT_OPTS: "-Dspark.jars.ivy=/tmp/ivy"
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./src:/opt/project/src
    restart: always

  # ---------- Spark Worker ----------
  spark-worker:
    build:
      context: ./docker/spark  
      dockerfile: Dockerfile
    container_name: spark-worker
    networks:
      - pipeline-net
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_CORES: 1
      PYTHONPATH: /opt/project/src
    volumes:
      - ./src:/opt/project/src
    depends_on:
      - spark-master
    restart: always

  # ---------- Airflow Webserver ----------
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  # ---------- Airflow Scheduler ----------
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always

  # ---------- Airflow Worker ----------
  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker
    restart: always

  # ---------- Airflow Init ----------
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username ${_AIRFLOW_WWW_USER_USERNAME:-airflow} \
          --password ${_AIRFLOW_WWW_USER_PASSWORD:-airflow} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    user: "0:0"
    volumes:
      - ./src:/opt/project/src
      - ./src/plugins:/opt/airflow/plugins
      - ./src/logs:/opt/airflow/logs


  # ---------- Spark worker weather streaming ----------
  spark-weather-streaming:
    build:
      context: ./docker/spark
      dockerfile: Dockerfile
    container_name: spark-weather-streaming
    networks:
      - pipeline-net
    env_file:
      - .env
    command: >
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --executor-memory 900m
      --executor-cores 1
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.hadoop:hadoop-aws:3.3.4
      /opt/project/src/spark/jobs/weather_streaming.py
    volumes:
      - ./src:/opt/project/src
    environment:
      PYTHONPATH: /opt/project/src
    depends_on:
      - spark-master
      - kafka
    restart: always

  # ---------- fastAPI local----------
  commute_fastapi:
    build:
      context: ./docker/fastapi
      dockerfile: Dockerfile
    container_name: commute_fastapi
    ports:
      - "8000:8000"
    networks:
      - pipeline-net
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PSWD}
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_HOST: ${APP_DB_HOST}
      POSTGRES_PORT: ${APP_DB_PORT}
      AIR_STATIONS_CSV: /app/dataset/air_stations.csv
      FCM_SERVICE_ACCOUNT_JSON: /app/secrets/fcm-service-account.json
      FCM_PROJECT_ID: commute-assistant-f2a53
    volumes:
      - ./fastapi:/app
      - ./dataset:/app/dataset
      - ./secrets/fcm-service-account.json:/app/secrets/fcm-service-account.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# ----------- redis for cache ------------
  redis-cache:
    image: redis:7.2-bookworm
    container_name: redis-cache
    networks:
      - pipeline-net
    volumes:
      - redis-cache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "6380:6379"


  # ----------- Postgres for App ---------------
  postgres-app:
    image: postgres:13
    container_name: postgres-app
    env_file:
      - .env
    networks:
      - pipeline-net
    volumes:
      - postgres-app-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PSWD}
      POSTGRES_DB: ${APP_DB_NAME}
      TZ: Asia/Seoul
      PGTZ: Asia/Seoul
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${APP_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


  # Google API scheduler - route
  route-scheduler:
    build:
      context: .
      dockerfile: docker/kafka/Dockerfile
    container_name: route-scheduler
    env_file:
      - .env
    volumes:
    - ./src/route_kafka/logs:/opt/project/logs
    - ./src:/opt/project/src
    networks:
      - pipeline-net
    restart: always
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      LOG_DIR: /opt/project/logs
      PYTHONPATH: /opt/project/src
      TZ: Asia/Seoul
    depends_on:
      kafka:
        condition: service_started
      postgres-app:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"


  route-worker:
    build:
      context: .
      dockerfile: docker/kafka_worker/Dockerfile
    container_name: route-worker
    env_file:
      - .env
    networks:
      - pipeline-net
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      PYTHONPATH: /opt/project/src
      TZ: Asia/Seoul
    depends_on:
      kafka:
        condition: service_started
      redis-cache:
        condition: service_healthy
    restart: always
