name: commute_assistant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  intl: ^0.18.1
  geocoding: ^2.1.1
  redis: ^4.0.0
  url_launcher: ^6.1.7
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/mask.png
    - assets/images/umbrella.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
